version: "3"
services:
  bedrockconnect:
    build: ./bedrockconnect
    ports:
      - "19132:19132/udp"
    volumes:
      - bedrockConnect:/brc
    env_file: 
      - "sql.env"
      - "brc.env"
    restart: "unless-stopped"
    stdin_open: true # docker run -i
    tty: true # docker run -t
  mysql:
    image: mariadb
    restart: "unless-stopped"
    volumes:
      - bedrockConnect:/var/lib/mysql
    env_file: sql.env
  bind9:
    build: 
      context: ./bind9
      args: 
        BCIP: ${BRCIP}
        NSIP: ${BRCIP}

#    env_file: "bind.env"
    ports: 
      -  ${BRCIP}:53:53/udp
#      -  53:53/udp
volumes:
  bedrockConnect:
    driver: local
